

CREATE TABLE J_Forms (
    ID SERIAL PRIMARY KEY,
    Task_Number varchar(255),
    Service_Group varchar(255),
    Service_Type varchar(255),
    Task_Priority varchar(255),
    Task_Status varchar(255),
    Assignee varchar(255),
    ppir_assignmentid varchar(255),
    ppir_insuranceid varchar(255),
    ppir_farmername varchar(255),
    ppir_address varchar(255),
    ppir_farmertype varchar(255),
    ppir_mobileno varchar(255),
    ppir_groupname varchar(255),
    ppir_groupaddress varchar(255),
    ppir_lendername varchar(255),
    ppir_lenderaddress varchar(255),
    ppir_cicno varchar(255),
    ppir_farmloc varchar(255),
    ppir_north varchar(255),
    ppir_south varchar(255),
    ppir_east varchar(255),
    ppir_west varchar(255),
    ppir_att_1 varchar(255),
    ppir_att_2 varchar(255),
    ppir_att_3 varchar(255),
    ppir_att_4 varchar(255),
    ppir_area_aci varchar(255),
    ppir_area_act varchar(255),
    ppir_dopds_aci varchar(255),
    ppir_dopds_act varchar(255),
    ppir_doptp_aci varchar(255),
    ppir_doptp_act varchar(255),
    ppir_svp_aci varchar(255),
    ppir_svp_act varchar(255),
    ppir_variety varchar(255),
    ppir_stagecrop varchar(255),
    ppir_remarks varchar(255),
    ppir_name_insured varchar(255),
    ppir_name_iuia varchar(255),
    ppir_sig_insured varchar(255),
    ppir_sig_iuia varchar(255)
);
